# pyproject.toml

[build-system]
requires = ["setuptools", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.setuptools.build_meta]
project_base = "src/NES/python_wrapper"

[project]
name = "omnicom"