name: OmniCom Python Wheel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel cibuildwheel pybind11
          pip freeze

      - name: Build wheels
        run: |
          python -m pip install setuptools wheel cibuildwheel pybind11
          pip freeze
          cibuildwheel --output-dir dist

      - name: Upload wheels to PyPI
        if: github.event_name == 'push'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install twine
          twine upload dist/*
