name: OmniCom Push Python Wheel

on:
  workflow_run:
    workflows: ["OmniCom Build Python Wheel"]
    types:
      - completed
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Upload wheels to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install twine
          twine upload --skip-existing --verbose dist/*
